### ISSUE TITLE
ERR_INVALID_ARG_TYPE exception thrown

### ISSUE THREAD

**Issue by epipheus** [HandyMiner/HandyMiner-Goldshell-GUI#2]
I get the following error when running the MacOS release:

```
AUTHORIZATION SUCCESS."}internal/fs/utils.js:701
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array
    at Object.writeFileSync (fs.js:1409:5)
    at /Applications/HandyMiner.app/Contents/Resources/app.nw/submodules/HandyMiner-Goldshell-CLI/miner/HandyMiner_GoldShell.js:596:14
    at Array.map ()
    at HandyMiner.parseServerResponse (/Applications/HandyMiner.app/Contents/Resources/app.nw/submodules/HandyMiner-Goldshell-CLI/miner/HandyMiner_GoldShell.js:563:10)
    at Socket. (/Applications/HandyMiner.app/Contents/Resources/app.nw/submodules/HandyMiner-Goldshell-CLI/miner/HandyMiner_GoldShell.js:350:28)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by smcki012** [comment]
Make sure you download from releases and run the unzipped file following the directions in the Readme. https://github.com/HandyMiner/HandyMiner-Goldshell-GUI/releases

**Comment by epipheus** [comment]
I believe I did that but will try again.  I definitely downloaded from releases.

**Comment by epipheus** [comment]
This btw, is the message from the logs tab in the HandyMiner.app

**Comment by epipheus** [comment]
Moreover, there really are no real instruction for the Mac release.  The repository home says downloading a release skips all below steps and the OSX release has no real instructions (unlike windows which says to download serial drivers, etc.) So other than downloading and copying to Applications, what instructions are you referring to follow? Are you just assuming there isn't a real issue?

**Comment by epipheus** [comment]
OSX 10.15.5

**Comment by smcki012** [comment]
Yes I believe this is a an issue with something on your end. Not the miner. You can also try the HandyMiner-Goldshell-CLI if you can't manage to get it to work.  

Also if you're using HNSPool, don't. Use DXpool and F2Pool for now. HNSPool pool has stratum issues. 

https://github.com/HandyMiner/HandyMiner-Goldshell-CLI

Go to http://t.me/HandshakeTalk we can help there. Closing this as we aren't Goldshell support, and that's our support channel.

**Comment by epipheus** [comment]
wow.
