### ISSUE TITLE
Request for MacOS 0.0.5 Executable

### ISSUE THREAD

**Issue by jflowers1974** [HandyMiner/HandyMiner-Goldshell-GUI#3]
I was wondering if a compiled version of 0.0.5 for MacOS could be uploaded.  Thanks

https://github.com/HandyMiner/HandyMiner-Goldshell-GUI/releases

**Comment by smcki012** [comment]
It's already live! It's on that link you provided.

**Comment by smcki012** [comment]
Oh oops. The draft wasn't published. On it.
