### ISSUE TITLE
Setup instructions could be clearer

### ISSUE THREAD

**Issue by brandondees** [HandyMiner/HandyMiner-Goldshell-GUI#4]
I just tried setting up my rig with Urkel pool (formerly hnspool) again today, and the setup instructions were not totally clear. In the GUI the dropdown option prompts for a single field Username. The hint text says use the payout address. The docs site says enter username and password, but there's no password field. I tried plugging in an address but it seemed like nothing was happening with the miner. Finally I settled on the email used for the account and after a few minutes it appears to be mining. I appreciate how simple this setup is, it's just not quite as self-explanatory as it could be.

**Comment by smcki012** [comment]
This is an issue with limited docs for HNSPool/Urkel Pool. Once they've clearer instructions, it'll be easier. Closing this issue.
